' File Path: /docs/srs/diagrams/state-machines/user-quest-attempt-state-machine.puml
@startuml

title "State Machine: UserQuestAttempt"
hide empty description

[*] --> InProgress : On Start Quest

state InProgress


state Paused


state Completed


state Abandoned

InProgress --> Paused : On User Pause Action
InProgress --> Completed : On Complete Final Objective
InProgress --> Abandoned : On User Abandon Action

Paused --> InProgress : On User Resume Action

@enduml