' submit-feedback-class.puml
@startuml
skinparam linetype ortho
skinparam ranksep 50
skinparam nodesep 50
skinparam classAttributeIconSize 0
hide empty members

package "API Layer" {
    class QuestFeedbackController {
        +SubmitFeedback(command)
    }
}

package "Application Layer" {
    class SubmitQuestStepFeedbackCommand {
        +AuthUserId
        +QuestId
        +StepId
        +Rating
        +Category
        +Comment
    }

    class SubmitQuestStepFeedbackCommandHandler {
        +Handle()
    }
}

package "Domain & Infrastructure Layer" {
    interface IUserQuestStepFeedbackRepository
    interface IQuestRepository
    interface IQuestStepRepository
    
    class UserQuestStepFeedback {
        +SubjectId
        +IsResolved
    }
}

' Relationships
QuestFeedbackController ..> SubmitQuestStepFeedbackCommand : Creates
QuestFeedbackController ..> SubmitQuestStepFeedbackCommandHandler : Sends

SubmitQuestStepFeedbackCommandHandler ..> SubmitQuestStepFeedbackCommand : Uses
SubmitQuestStepFeedbackCommandHandler --> IUserQuestStepFeedbackRepository
SubmitQuestStepFeedbackCommandHandler --> IQuestRepository
SubmitQuestStepFeedbackCommandHandler --> IQuestStepRepository
SubmitQuestStepFeedbackCommandHandler ..> UserQuestStepFeedback : Creates

@enduml