' RougeLearn.BMAD.Documentation/docs/srs/diagrams/class-diagram/quest-learning/generate-quest-line-class.puml
@startuml
skinparam linetype ortho
skinparam ranksep 50
skinparam nodesep 50
skinparam classAttributeIconSize 0
hide empty members

package "Application Layer" {
    class GenerateQuestLineCommand {
        +AuthUserId
    }

    class GenerateQuestLineCommandHandler {
        +Handle()
        -DetermineRecommendationReason()
    }
}

package "Domain & Infrastructure Layer" {
    interface ISubjectRepository
    interface IClassSpecializationSubjectRepository
    interface IStudentSemesterSubjectRepository
    interface IQuestRepository
    interface IQuestChapterRepository
    
    class Quest {
        +IsRecommended
        +RecommendationReason
    }
}

' Relationships
GenerateQuestLineCommandHandler ..> GenerateQuestLineCommand : Uses

GenerateQuestLineCommandHandler --> ISubjectRepository
GenerateQuestLineCommandHandler --> IClassSpecializationSubjectRepository
GenerateQuestLineCommandHandler --> IStudentSemesterSubjectRepository
GenerateQuestLineCommandHandler --> IQuestRepository
GenerateQuestLineCommandHandler --> IQuestChapterRepository

IQuestRepository ..> Quest : Manages
@enduml