' get-step-activities-class.puml
@startuml
skinparam linetype ortho
skinparam ranksep 50
skinparam nodesep 50
skinparam classAttributeIconSize 0
hide empty members

package "API Layer" {
    class UserQuestProgressController {
        +GetStepActivities()
    }
}

package "Application Layer" {
    class GetCompletedActivitiesQuery {
        +StepId
    }

    class GetCompletedActivitiesQueryHandler {
        +Handle()
        -ExtractAndMapActivities()
    }
}

package "Domain & Infrastructure Layer" {
    interface IQuestStepRepository
    interface IUserQuestStepProgressRepository
    
    class CompletedActivitiesDto {
        +List<ActivityProgressDto>
    }
}

UserQuestProgressController ..> GetCompletedActivitiesQuery : Creates
UserQuestProgressController ..> GetCompletedActivitiesQueryHandler : Sends

GetCompletedActivitiesQueryHandler --> IQuestStepRepository
GetCompletedActivitiesQueryHandler --> IUserQuestStepProgressRepository
GetCompletedActivitiesQueryHandler ..> CompletedActivitiesDto : Returns
@enduml